### ISSUE TITLE
Allow using the Action together with testing-library

### ISSUE THREAD

**Issue by Vinnl** [DevExpress/testcafe-action#17]
I think this might be related to #13: if I add [`@testing-library/testcafe`](https://testing-library.com/docs/testcafe-testing-library/intro) as a dependency and run `npm install` before running the action, I still [get](https://github.com/inrupt/solid-client-authn-js/runs/1242218111?check_suite_focus=true) an error that says that an import from that library is undefined:

> Error: Cannot call method 'queryByRole' of undefined

It does work when running the tests using `npx testcafe` locally.

**Comment by Ogurecher** [comment]
@Vinnl, `testcafe-testing-library`[depends on testcafe](https://github.com/testing-library/testcafe-testing-library/blob/master/package.json#L38), which means that you'll have to add `testcafe` to your `package.json` as well. This makes the use of `testcafe-action` redundant, as in this case `testcafe` is already going to be installed via the `npm ci` command. If you use `testcafe-action` after that, `testcafe` will be installed for the second time.
Your dependencies should look as follows:
```
"dependencies": {
    "@testing-library/testcafe": "^4.2.3",
    "testcafe": "^1.9.4"
}
```
And you can `- run` testcafe in your `.yml` instead of using `DevExpress/testcafe-action@latest`.

**Comment by Vinnl** [comment]
Ah, I thought the Action did more than just installing the dependency, i.e. that it also set up the browsers and a headless X environment. I'll try to set it up without the Action next week then. Thanks for the response!

**Comment by Vinnl** [comment]
For anyone coming across this later, running TestCafe in GitHub Actions without using the GitHub Action is indeed very straightforward. All I had to do was running it just like usual, except for making sure to use the headless versions of browsers, i.e.:

```
npx testcafe firefox:headless,chrome:headless some.test.ts
```
