### ISSUE TITLE
Does not take working-directory into account

### ISSUE THREAD

**Issue by cattermo** [DevExpress/testcafe-action#18]
If I have set working-directory for the job testcafe action should run inside that directory. It seems to be running inside root always.

**Comment by miherlosev** [comment]
Hi @cattermo 

Could please share an example that illustrates the problematic behavior?

**Comment by cattermo** [comment]
I have a monorepo where different micro services where end-to-end tests covers all of those. Each service is located inside folders down the tree, e.g. src/my-micro-service, where it has its own package.json, dependencies and code.

Our end-to-end tests cover all the micro services and are located in src/end-to-end folder. Locally you would always run testcafe from this folder. Testcafe config and screenshots live here.

When creating github workflows for this monorepo I cannot get the end-to-end tests to run inside src/end-to-end folder even though I set like this for the whole workflow: 
```
defaults:
  run:
    working-directory: 'src/end-to-end'
```
It will still try to run from root.

**Comment by miherlosev** [comment]
We need a public example with which we can reproduce the problem without any additional setup. 
Please feel free to reopen the issue if you can share such an example with us.

**Comment by Jackman3005** [comment]
I am also experiencing this. Doesn't seem hard to reproduce, just have a subfolder with your testcafe tests and the associated package.json file and it will not work out of the box. It ignores the configured working directory as mentioned above.

I can force it to use the correct config file with the `--config-file` argument, but then it fails because ffmpeg isn't loaded, because it's looking at the package.json at the root of the project instead of the package.json in the e2e folder...

**Comment by Aleksey28** [comment]
Please share an example where the issue is reproduced without additional setup.
