### ISSUE TITLE
Can't find firefox on ubuntu-latest

### ISSUE THREAD

**Issue by nnnnat** [DevExpress/testcafe-action#31]
Hey y'all, I've been using this action as part of my CI process & I suddenly started getting failures that testcafe can't find `firefox:headless`. 

```
ERROR Cannot find the browser. "firefox:headless" is neither a known browser alias, nor a path to an executable file.
```

I had this action configured to run on `ubuntu-latest` which was updated recently to be Ubuntu 22.04 ([blog post](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/)). Looks like Ubuntu 22.04 ships with a [different firefox](https://github.com/actions/runner-images/issues/6399#issuecomment-1284409180) setup than previous versions which is what I believe is causing this issue. I was able to test that `chrome:headless` still works on `ubuntu-latest` & that pinning to the previous version of ubuntu (`ubuntu-20.04`) works with both `chrome:headless` & `firefox:headless`. 

I don't think this is really an issue with the action but the change to the runner-images. Thought this might be helpful context for anyone else struggling with random failures while using `ubuntu-latest` to test against firefox.

**Comment by Aleksey28** [comment]
Hi @nnnnat,

It happens because [there is no Firefox in GitHub actions for Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md). You need to manually install it. Look at the following topic to learn how to do this in the right way: [https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04](https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04)
